all:
	  python geraMatriz.py 400 400 && \
	  echo "\n\n Iteração 1\n" && \
	  echo "\n\nBUSCA TABU\n" && \
	  python buscaTabu.py && \
	  echo "\n\nGRASP\n" && \
	  python grasp2.py && \
		echo "-------------------------------------------------------------------" && \
	  echo "\n\n Iteração 2\n" && \
		echo "\n\nBUSCA TABU\n" && \
	  python buscaTabu.py && \
	  echo "\n\nGRASP\n" && \
	  python grasp2.py && \
		echo "-------------------------------------------------------------------" && \
	  echo "\n\n Iteração 3\n" && \
		echo "\n\nBUSCA TABU\n" && \
	  python buscaTabu.py && \
	  echo "\n\nGRASP\n" && \
	  python grasp2.py && \
		echo "-------------------------------------------------------------------" && \
	  echo "\n\n Iteração 4\n" && \
		echo "\n\nBUSCA TABU\n" && \
	  python buscaTabu.py && \
	  echo "\n\nGRASP\n" && \
	  python grasp2.py && \
		echo "-------------------------------------------------------------------" && \
	  echo "\n\n Iteração 5\n" && \
		echo "\n\nBUSCA TABU\n" && \
	  python buscaTabu.py && \
	  echo "\n\nGRASP\n" && \
	  python grasp2.py && \
		echo "-------------------------------------------------------------------" && \
	  echo "\n\n Iteração 6\n" && \
		echo "\n\nBUSCA TABU\n" && \
	  python buscaTabu.py && \
	  echo "\n\nGRASP\n" && \
	  python grasp2.py && \
		echo "-------------------------------------------------------------------" && \
	  echo "\n\n Iteração 7\n" && \
		echo "\n\nBUSCA TABU\n" && \
	  python buscaTabu.py && \
	  echo "\n\nGRASP\n" && \
	  python grasp2.py && \
		echo "-------------------------------------------------------------------" && \
	  echo "\n\n Iteração 8\n" && \
		echo "\n\nBUSCA TABU\n" && \
	  python buscaTabu.py && \
	  echo "\n\nGRASP\n" && \
	  python grasp2.py && \
		echo "-------------------------------------------------------------------" && \
	  echo "\n\n Iteração 9\n" && \
		echo "\n\nBUSCA TABU\n" && \
	  python buscaTabu.py && \
	  echo "\n\nGRASP\n" && \
	  python grasp2.py && \
		echo "-------------------------------------------------------------------" && \
	  echo "\n\n Iteração 10\n" && \
		echo "\n\nBUSCA TABU\n" && \
	  python buscaTabu.py && \
	  echo "\n\nGRASP\n" && \
	  python grasp2.py && \
		echo "-------------------------------------------------------------------" && \
	  echo "Finish!"
